server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: orders
  sslmode: disable

kafka:
  brokers:
    - kafka:9092
  orderTopic: order-events
  paymentTopic: payment-events

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
